import { StyleSheet, Platform, StatusBar } from 'react-native';

export function createHomeStyles(t) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: t.background, paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight ?? 0 : 0 },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 40 },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: Platform.OS === 'android' ? 24 : 20, paddingBottom: 12 },
    logoRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    logoBox: { width: 34, height: 34, backgroundColor: t.primarySoft, borderWidth: 0, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    appName: { fontSize: 18, fontWeight: '800', color: t.textPrimary, letterSpacing: -0.4 },
    iconBtn: { width: 36, height: 36, backgroundColor: t.surface, borderWidth: 1, borderColor: t.borderSubtle, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    greeting: { paddingHorizontal: 20, paddingBottom: 20 },
    greetingMain: { fontSize: 22, fontWeight: '800', color: t.textPrimary, letterSpacing: -0.5, lineHeight: 28 },
    greetingSub: { fontSize: 13, color: t.textSecondary, marginTop: 4 },
    progressCard: {
      marginHorizontal: 16,
      marginBottom: 20,
      backgroundColor: t.elevatedSurface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: t.borderSubtle,
      padding: 20,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 20,
      shadowColor: t.shadow,
      shadowOpacity: t.cardShadowOpacity,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 4 },
      elevation: t.cardElevation,
    },
    ringPct: { fontSize: 18, fontWeight: '800', color: t.textPrimary, lineHeight: 22 },
    ringLabel: { fontSize: 9, color: t.textTertiary, fontWeight: '500', marginTop: 1, letterSpacing: 0.3 },
    progressInfo: { flex: 1 },
    progressEyebrow: { fontSize: 9, fontWeight: '700', color: t.textTertiary, letterSpacing: 1.2, marginBottom: 4 },
    progressHeading: { fontSize: 17, fontWeight: '800', color: t.textPrimary, marginBottom: 2 },
    progressBarRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10 },
    progressBarBg: { flex: 1, height: 5, backgroundColor: t.borderLight, borderRadius: 99, overflow: 'hidden' },
    progressBarFill: { height: '100%', backgroundColor: t.progressPrimary, borderRadius: 99 },
    progressBarPct: { fontSize: 11, fontWeight: '700', color: t.progressPrimary },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 12, paddingTop: 4 },
    sectionTitle: { fontSize: 15, fontWeight: '700', color: t.textPrimary },
    sectionLink: { fontSize: 12, fontWeight: '600', color: t.primary },
    tasksList: { paddingHorizontal: 16, gap: 8, marginBottom: 20 },
    tasksEmpty: {
      marginHorizontal: 16,
      marginBottom: 20,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.borderSubtle,
      borderRadius: 14,
      paddingVertical: 28,
      paddingHorizontal: 20,
      alignItems: 'center',
      shadowColor: t.shadow,
      shadowOpacity: t.cardShadowOpacity,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: t.cardElevation,
    },
    tasksEmptyTitle: { fontSize: 15, fontWeight: '700', color: t.textPrimary, textAlign: 'center', marginBottom: 6 },
    tasksEmptySub: { fontSize: 12, color: t.textSecondary, textAlign: 'center', lineHeight: 18 },
    taskRow: {
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.borderSubtle,
      borderRadius: 14,
      padding: 13,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      shadowColor: t.shadow,
      shadowOpacity: t.cardShadowOpacity,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: t.cardElevation,
    },
    taskCheck: { width: 22, height: 22, borderRadius: 7, flexShrink: 0, alignItems: 'center', justifyContent: 'center' },
    taskCheckDone: { backgroundColor: t.primary },
    taskCheckUndone: { borderWidth: 2, borderColor: t.textTertiary, backgroundColor: t.surface },
    taskBody: { flex: 1 },
    taskTitle: { fontSize: 13, fontWeight: '600', color: t.textPrimary, lineHeight: 18 },
    taskTitleDone: { color: t.textTertiary, textDecorationLine: 'line-through' },
    taskMeta: { fontSize: 11, color: t.textTertiary, marginTop: 2 },
    taskTag: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 7 },
    taskTagText: { fontSize: 10, fontWeight: '700', letterSpacing: 0.2 },
    focusCard: { marginHorizontal: 16, marginBottom: 20, backgroundColor: t.primary, borderRadius: 20, padding: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', elevation: 6 },
    focusEyebrow: { fontSize: 9, fontWeight: '700', color: 'rgba(255,255,255,0.7)', letterSpacing: 1.2, marginBottom: 4 },
    focusTime: { fontSize: 24, fontWeight: '800', color: t.onPrimary, letterSpacing: -0.5 },
    focusSub: { fontSize: 12, color: 'rgba(255,255,255,0.7)', marginTop: 3 },
    focusBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(255,255,255,0.18)', borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.3)', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 11 },
    focusBtnText: { fontSize: 12, fontWeight: '700', color: t.onPrimary },
  });
}
