import { palette } from './colors';

export const lightTheme = {
  mode: 'light',
  background: '#F8FAFC',
  backgroundSecondary: '#F8FAFC',
  surface: '#FFFFFF',
  secondarySurface: '#F1F5F9',
  elevatedSurface: '#FFFFFF',
  tabBarBackground: '#FFFFFF',
  searchBackground: '#FFFFFF',
  primary: '#3B82F6',
  primaryPressed: '#2563EB',
  primarySoft: '#EFF6FF',
  primarySoftBorder: '#BFDBFE',
  accent: '#60A5FA',
  progressPrimary: '#3B82F6',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  textTertiary: '#94A3B8',
  border: '#E2E8F0',
  borderSubtle: '#E2E8F0',
  borderLight: '#F1F5F9',
  inputBg: '#F8FAFC',
  overlay: 'rgba(0,0,0,0.35)',
  shadow: '#000000',
  cardShadowOpacity: 0.04,
  cardElevation: 2,
  statusBarStyle: 'dark-content',
  switchTrackFalse: '#E2E8F0',
  switchTrackTrue: '#BFDBFE',
  switchThumbOn: '#3B82F6',
  switchThumbOff: '#CBD5E1',
  onPrimary: '#FFFFFF',
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  errorBorder: '#FECACA',
  priority: {
    High: { bg: '#FEF2F2', text: '#EF4444' },
    Medium: { bg: '#FFFBEB', text: '#F59E0B' },
    Low: { bg: '#F0FDF4', text: '#22C55E' },
  },
  chartMuted: '#DBEAFE',
  chartLight: '#BFDBFE',
  chartMid: '#93C5FD',
  chartStrong: '#3B82F6',
  focusGreenMuted: '#BBF7D0',
  focusGreenLight: '#4ADE80',
  focusGreenMid: '#86EFAC',
  focusGreenStrong: '#22C55E',
};
