import { StyleSheet, Platform, StatusBar } from 'react-native';

export function createSettingsStyles(t) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: t.background, paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight ?? 0 : 0 },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 40, paddingHorizontal: 16 },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: Platform.OS === 'android' ? 16 : 12, paddingBottom: 12 },
    backBtn: { width: 36, height: 36, backgroundColor: t.surface, borderWidth: 1, borderColor: t.borderSubtle, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    headerTitle: { fontSize: 16, fontWeight: '700', color: t.textPrimary, letterSpacing: -0.2 },
    avatarSection: { alignItems: 'center', paddingVertical: 24 },
    avatarWrap: { position: 'relative', marginBottom: 12 },
    avatarEditBadge: { position: 'absolute', bottom: 0, right: 0, width: 28, height: 28, borderRadius: 14, backgroundColor: t.elevatedSurface, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: t.background },
    nameRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
    nameText: { fontSize: 20, fontWeight: '800', color: t.textPrimary, letterSpacing: -0.4 },
    nameEditRow: { marginBottom: 6, width: '60%' },
    nameInput: { fontSize: 20, fontWeight: '800', color: t.textPrimary, borderBottomWidth: 2, borderBottomColor: t.primary, paddingVertical: 4, textAlign: 'center' },
    avatarHint: { fontSize: 11, color: t.textTertiary, textAlign: 'center' },
    sectionLabel: { fontSize: 10, fontWeight: '700', color: t.textTertiary, letterSpacing: 1.4, marginTop: 20, marginBottom: 8, marginLeft: 4 },
    card: {
      backgroundColor: t.elevatedSurface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: t.borderSubtle,
      paddingHorizontal: 16,
      paddingVertical: 6,
      shadowColor: t.shadow,
      shadowOpacity: t.cardShadowOpacity,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 3 },
      elevation: t.cardElevation,
    },
    divider: { height: 1, backgroundColor: t.borderLight, marginVertical: 2 },
    fieldWrap: { paddingVertical: 12 },
    fieldLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
    fieldLabel: { fontSize: 12, fontWeight: '600', color: t.textPrimary },
    requiredBadge: { fontSize: 9, fontWeight: '700', color: t.primary, backgroundColor: t.primarySoft, borderRadius: 5, paddingHorizontal: 6, paddingVertical: 2, letterSpacing: 0.4 },
    fieldInput: { backgroundColor: t.inputBg, borderWidth: 1, borderColor: t.border, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: t.textPrimary, fontWeight: '500' },
    fieldInputMulti: { height: 80, textAlignVertical: 'top' },
    fieldInputError: { borderColor: t.errorBorder, backgroundColor: t.priority.High.bg },
    fieldError: { fontSize: 11, color: t.error, marginTop: 5 },
    contactError: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, backgroundColor: t.priority.High.bg, borderRadius: 9, padding: 10, marginTop: 4, marginBottom: 6, borderWidth: 1, borderColor: t.errorBorder },
    contactErrorText: { fontSize: 12, color: t.error, flex: 1, lineHeight: 17 },
    focusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2 },
    focusChip: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 9, borderWidth: 1, borderColor: t.borderSubtle, backgroundColor: t.inputBg },
    focusChipActive: { backgroundColor: t.primarySoft, borderColor: t.primary },
    focusChipText: { fontSize: 12, fontWeight: '600', color: t.textSecondary },
    focusChipTextActive: { color: t.primary },
    toggleRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, gap: 12 },
    toggleRowBorder: { borderBottomWidth: 1, borderBottomColor: t.borderLight },
    toggleIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    toggleText: { flex: 1 },
    toggleLabel: { fontSize: 14, fontWeight: '600', color: t.textPrimary },
    toggleSub: { fontSize: 11, color: t.textTertiary, marginTop: 1 },
    saveBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: t.primary, borderRadius: 14, paddingVertical: 15, marginTop: 24, shadowColor: t.primary, shadowOpacity: 0.3, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 5 },
    saveBtnPressed: { backgroundColor: t.primaryPressed, shadowOpacity: 0.15 },
    saveBtnText: { fontSize: 15, fontWeight: '700', color: t.onPrimary, letterSpacing: 0.2 },
    logoutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: t.priority.High.bg, borderWidth: 1, borderColor: t.errorBorder, borderRadius: 14, paddingVertical: 14, marginTop: 12 },
    logoutBtnPressed: { opacity: 0.85 },
    logoutBtnText: { fontSize: 15, fontWeight: '600', color: t.error },
  });
}
