import { useMemo } from 'react';
import { StyleSheet, Platform, StatusBar } from 'react-native';
import { useTheme } from './ThemeProvider';

export function createTaskScreenStyles(t) {
  const s = StyleSheet.create({
    safe: { flex: 1, backgroundColor: t.background, paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight ?? 0 : 0 },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 12 },
    headerTitle: { fontSize: 22, fontWeight: '800', color: t.textPrimary },
    headerSub: { fontSize: 12, color: t.textTertiary },
    iconBtn: { width: 36, height: 36, backgroundColor: t.surface, borderWidth: 1, borderColor: t.borderSubtle, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    badge: { position: 'absolute', top: -5, right: -5, minWidth: 16, height: 16, backgroundColor: t.error, borderRadius: 99, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: t.background },
    badgeText: { fontSize: 9, fontWeight: '800', color: t.onPrimary },
    searchWrap: { paddingHorizontal: 16, marginVertical: 16 },
    searchBox: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: t.searchBackground, borderWidth: 1, borderColor: t.border, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 11 },
    searchInput: { flex: 1, fontSize: 14, color: t.textPrimary },
    filtersScroll: { flexGrow: 0, flexShrink: 0, marginBottom: 12 },
    filtersRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 10 },
    chip: { paddingHorizontal: 16, paddingVertical: 7, borderRadius: 99, borderWidth: 1.5 },
    chipActive: { backgroundColor: t.primary, borderColor: t.primary },
    chipInactive: { backgroundColor: t.surface, borderColor: t.borderSubtle },
    chipText: { fontSize: 12, fontWeight: '700' },
    chipTextActive: { color: t.onPrimary },
    chipTextInactive: { color: t.textSecondary },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 100 },
    sectionLbl: { paddingHorizontal: 20, paddingBottom: 10, fontSize: 11, fontWeight: '700', color: t.textTertiary, letterSpacing: 1 },
    taskList: { paddingHorizontal: 16, gap: 8 },
    sep: { height: 1, backgroundColor: t.borderLight, marginHorizontal: 16, marginVertical: 16 },
    taskCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.borderSubtle,
      borderRadius: 16,
      padding: 14,
      gap: 12,
      shadowColor: t.shadow,
      shadowOpacity: t.cardShadowOpacity,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: t.cardElevation,
    },
    taskCardPressed: { backgroundColor: t.secondarySurface },
    checkbox: { width: 22, height: 22, borderRadius: 7, alignItems: 'center', justifyContent: 'center' },
    cbDone: { backgroundColor: t.primary },
    cbUndone: { borderWidth: 2, borderColor: t.textTertiary, backgroundColor: t.surface },
    taskBody: { flex: 1 },
    taskTitle: { fontSize: 13, fontWeight: '600', color: t.textPrimary },
    taskTitleDone: { color: t.textTertiary, textDecorationLine: 'line-through' },
    taskSubRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 3 },
    taskSub: { fontSize: 11, color: t.textTertiary },
    tag: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 7 },
    tagText: { fontSize: 10, fontWeight: '700' },
    fab: { position: 'absolute', bottom: 24, right: 20, width: 54, height: 54, backgroundColor: t.primary, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
    emptyWrap: { alignItems: 'center', paddingTop: 60, gap: 10 },
    emptyIcon: { width: 72, height: 72, backgroundColor: t.secondarySurface, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
    emptyTitle: { fontSize: 16, fontWeight: '700', color: t.textPrimary },
    emptySub: { fontSize: 13, color: t.textTertiary, textAlign: 'center' },
    emptyBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: t.primarySoft, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 10 },
    emptyBtnText: { fontSize: 13, fontWeight: '700', color: t.primary },
  });

  const a = StyleSheet.create({
    overlay: { flex: 1, backgroundColor: t.overlay },
    sheet: { backgroundColor: t.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingBottom: 24, paddingTop: 12 },
    handle: { width: 36, height: 4, backgroundColor: t.border, borderRadius: 99, alignSelf: 'center', marginBottom: 16 },
    preview: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 14 },
    previewTitle: { flex: 1, fontSize: 15, fontWeight: '700', color: t.textPrimary },
    previewTag: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
    previewTagText: { fontSize: 11, fontWeight: '700' },
    divider: { height: 1, backgroundColor: t.borderLight, marginHorizontal: 20, marginBottom: 4 },
    action: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 20, paddingVertical: 14 },
    actionIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    actionBody: { flex: 1 },
    actionTitle: { fontSize: 14, fontWeight: '600', color: t.textPrimary },
    actionSub: { fontSize: 12, color: t.textTertiary },
    cancelBtn: { marginHorizontal: 16, marginTop: 8, backgroundColor: t.inputBg, borderWidth: 1, borderColor: t.border, borderRadius: 14, paddingVertical: 14, alignItems: 'center' },
    cancelText: { fontSize: 14, fontWeight: '700', color: t.textSecondary },
  });

  const m = StyleSheet.create({
    modalRoot: { flex: 1, justifyContent: 'flex-end' },
    overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: t.overlay },
    kvContainer: { width: '100%', maxHeight: '92%', justifyContent: 'flex-end' },
    sheetSafe: { width: '100%', flexShrink: 1 },
    sheet: { backgroundColor: t.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '100%', width: '100%', overflow: 'hidden', flexShrink: 1 },
    sheetScroll: { flexGrow: 0, flexShrink: 1 },
    sheetScrollContent: { paddingHorizontal: 20, paddingTop: 12 },
    handle: { width: 36, height: 4, backgroundColor: t.border, borderRadius: 99, alignSelf: 'center', marginTop: 12, marginBottom: 16 },
    sheetTitle: { fontSize: 18, fontWeight: '800', marginBottom: 20, color: t.textPrimary },
    label: { fontSize: 12, fontWeight: '700', color: t.textSecondary, marginBottom: 8 },
    required: { color: t.error },
    errorText: { fontSize: 11, color: t.error, marginTop: -10, marginBottom: 12, fontWeight: '600' },
    input: { backgroundColor: t.inputBg, borderWidth: 1.5, borderColor: t.border, borderRadius: 12, padding: 14, marginBottom: 16, color: t.textPrimary },
    inputError: { borderColor: t.errorBorder },
    suggestRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
    suggestChip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 99, borderWidth: 1.5, borderColor: t.border, backgroundColor: t.surface },
    suggestChipActive: { borderColor: t.primary, backgroundColor: t.primarySoft },
    suggestChipText: { fontSize: 11, fontWeight: '700', color: t.textSecondary },
    suggestChipTextActive: { color: t.primary },
    quickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
    quickChip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 99, backgroundColor: t.primarySoft, borderWidth: 1, borderColor: t.primarySoftBorder },
    quickChipText: { fontSize: 11, fontWeight: '700', color: t.primary },
    clearChip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 99, backgroundColor: t.inputBg, borderWidth: 1, borderColor: t.border },
    clearChipText: { fontSize: 11, fontWeight: '700', color: t.textSecondary },
    dueRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
    dueBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: t.inputBg, borderWidth: 1.5, borderColor: t.border, borderRadius: 12, padding: 14 },
    dueBtnText: { flex: 1, fontSize: 13, fontWeight: '600', color: t.textPrimary },
    dueIconBtn: { width: 48, height: 48, backgroundColor: t.inputBg, borderWidth: 1.5, borderColor: t.border, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    tagRow: { flexDirection: 'row', gap: 10, marginBottom: 8 },
    tagChip: { flex: 1, paddingVertical: 10, borderRadius: 10, borderWidth: 1.5, borderColor: t.border, alignItems: 'center' },
    tagChipError: { borderColor: t.errorBorder },
    tagChipText: { fontSize: 12, fontWeight: '700' },
    btnRow: { flexDirection: 'row', gap: 10 },
    cancelBtn: { flex: 1, paddingVertical: 14, backgroundColor: t.inputBg, borderRadius: 14, alignItems: 'center' },
    cancelText: { fontSize: 14, fontWeight: '700', color: t.textSecondary },
    saveBtn: { flex: 2, paddingVertical: 14, backgroundColor: t.primary, borderRadius: 14, alignItems: 'center' },
    saveBtnDisabled: { backgroundColor: t.textTertiary },
    saveText: { fontSize: 14, fontWeight: '700', color: t.onPrimary },
  });

  const ar = StyleSheet.create({
    overlay: { flex: 1, backgroundColor: t.overlay },
    sheet: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: t.background, borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '88%', paddingTop: 12 },
    handle: { width: 36, height: 4, backgroundColor: t.border, borderRadius: 99, alignSelf: 'center', marginBottom: 16 },
    sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: t.border },
    sheetTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    sheetIconWrap: { width: 38, height: 38, backgroundColor: t.surface, borderWidth: 1, borderColor: t.border, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
    sheetTitle: { fontSize: 17, fontWeight: '800', color: t.textPrimary },
    sheetSub: { fontSize: 12, color: t.textTertiary },
    closeBtn: { width: 32, height: 32, backgroundColor: t.secondarySurface, borderRadius: 99, alignItems: 'center', justifyContent: 'center' },
    scroll: { flex: 1 },
    scrollContent: { paddingHorizontal: 16, paddingTop: 20 },
    sectionLbl: { fontSize: 11, fontWeight: '700', color: t.textTertiary, marginBottom: 10 },
    sep: { height: 1, backgroundColor: t.border, marginVertical: 20 },
    card: { backgroundColor: t.surface, borderWidth: 1, borderColor: t.border, borderRadius: 16, padding: 14, marginBottom: 8 },
    cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
    typeChip: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 7 },
    typeCompleted: { backgroundColor: t.priority.Low.bg },
    typeDeleted: { backgroundColor: t.priority.High.bg },
    typeText: { fontSize: 10, fontWeight: '700' },
    title: { fontSize: 13, fontWeight: '600', marginBottom: 4, color: t.textPrimary },
    subRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 12 },
    sub: { fontSize: 11, color: t.textTertiary, flex: 1 },
    actions: { flexDirection: 'row', gap: 8 },
    restoreBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 9, backgroundColor: t.primarySoft, borderRadius: 10 },
    deleteBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 9, backgroundColor: t.priority.High.bg, borderRadius: 10 },
    btnPressed: { opacity: 0.7 },
    restoreText: { fontSize: 12, fontWeight: '700', color: t.primary },
    deleteText: { fontSize: 12, fontWeight: '700', color: t.error },
    emptyWrap: { alignItems: 'center', paddingTop: 60, gap: 10 },
    emptyIcon: { width: 72, height: 72, backgroundColor: t.secondarySurface, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
    emptyTitle: { fontSize: 16, fontWeight: '700', color: t.textPrimary },
    emptySub: { fontSize: 13, color: t.textTertiary, textAlign: 'center' },
  });

  return { s, a, m, ar };
}

export function useTaskScreenStyles() {
  const { theme } = useTheme();
  return useMemo(() => createTaskScreenStyles(theme), [theme]);
}
