import { StyleSheet } from 'react-native';
import { colors, spacing } from './styles/tokens';

export const palette = {
  blue: colors.blue500,
  blueDark: colors.blue600,
  bgTop: colors.sky50,
  bgBottom: colors.sky100,
  card: colors.white,
  textPrimary: colors.gray900,
  textSecondary: colors.gray500,
  border: colors.gray200,
  white: colors.white,
  danger: colors.danger600,
};

const alpha = {
  shapePrimary: 'rgba(219,234,254,0.42)',
  shapeSecondary: 'rgba(224,231,255,0.32)',
  cardBackground: 'rgba(255,255,255,0.78)',
  cardBorder: 'rgba(255,255,255,0.65)',
  statusBackground: 'rgba(59,130,246,0.08)',
  statusBorder: 'rgba(147,197,253,0.55)',
  inputBorder: 'rgba(203,213,225,0.9)',
  inputBackground: 'rgba(248,250,252,0.98)',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.bgTop },
  flex: { flex: 1 },
  backgroundRoot: { ...StyleSheet.absoluteFillObject },
  abstractShape: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: colors.blue100,
    opacity: 0.42,
  },
  abstractShapeTop: { width: 250, height: 250, top: -60, right: -70 },
  abstractShapeMid: {
    width: 180,
    height: 180,
    top: 120,
    left: -60,
    backgroundColor: colors.indigo100,
    opacity: 0.32,
  },
  abstractShapeBottom: {
    width: 240,
    height: 240,
    bottom: -80,
    left: -70,
    backgroundColor: colors.blue200,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing['2xl'],
  },
  card: {
    backgroundColor: alpha.cardBackground,
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingVertical: 26,
    borderWidth: 1,
    borderColor: alpha.cardBorder,
    shadowColor: colors.slate900,
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
  subheading: {
    marginTop: 10,
    fontSize: 14,
    color: palette.textSecondary,
    textAlign: 'center',
    lineHeight: 21,
  },
  statusPill: {
    marginTop: 18,
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: alpha.statusBackground,
    borderWidth: 1,
    borderColor: alpha.statusBorder,
  },
  statusPillText: {
    color: '#1D4ED8',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.15,
  },
  formWrap: { marginTop: spacing['2xl'] },
  formPanel: { gap: 2 },
  fieldBlock: { marginBottom: spacing.lg },
  fieldLabel: {
    marginBottom: spacing.sm,
    marginLeft: spacing.xs,
    color: colors.slate600,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  inputShell: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: alpha.inputBorder,
    backgroundColor: alpha.inputBackground,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    shadowColor: colors.slate900,
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  inputShellFocused: {
    borderColor: colors.blue600,
    backgroundColor: colors.white,
    shadowColor: colors.blue600,
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  leadingIcon: {
    width: 18,
    marginRight: spacing.md,
    color: colors.slate500,
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '700',
  },
  input: { flex: 1, color: colors.slate900, fontSize: 15, paddingVertical: 0 },
  trailingIconButton: { marginLeft: spacing.md },
  trailingIcon: { color: colors.blue600, fontSize: 13, fontWeight: '700' },
  forgotWrap: { alignSelf: 'flex-end', marginTop: spacing.xs, marginBottom: 18 },
  forgotText: { color: palette.blue, fontSize: 14, fontWeight: '600' },
  errorText: {
    marginTop: 14,
    color: palette.danger,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  footerSwitch: { marginTop: 18, alignSelf: 'center' },
  footerText: { color: palette.textSecondary, fontSize: 14, lineHeight: 20 },
  footerAction: { color: palette.blue, fontWeight: '700' },
  primaryBtn: { marginTop: spacing.sm },
});
